### ISSUE TITLE
Typo in Dockerfile

### ISSUE THREAD

**Issue by GPhilo** [Edwardmark/caffe-docker#1]
On [line 52 of the Dockerfile](https://github.com/Edwardmark/caffe-docker/blob/a6cd509cf786b13e0e1d77fca77690da31618455/Dockerfile#L52) there's a `---upgrade` which has a "-" too many. This will break the setup when running `docker-build.sh`.

**Comment by GPhilo** [comment]
Also, while I'm at it, I'll report that ipython's setup also fails (you search for version >= 3.0.0 but from 6.0 on it's only compatible with python 3.3+).

**Comment by Edwardmark** [comment]
@GPhilo Thank you for bug report, I'll try to fixed it soon.

**Comment by Edwardmark** [comment]
@GPhilo I fixed the typo, and  I didn't test with ipython,  exept that is anything wrong?

**Comment by GPhilo** [comment]
@Edwardmark The ipython error comes from the `requirements.txt` file you fetch from Caffe. In there, you have "ipython >= 3.0.0" but that gets matched to ipython 6.0, which won't install because you have python 2.7 on the machine. You need to change the requirement s.t. you get ipython >= 3.0.0, ipython <= 5 (I don't know what's the proper pip syntax for that).

**Comment by Edwardmark** [comment]
@GPhilo I just change it to ipython==3.0.0, it can solve the issue.
